# Generated by Django 4.2.7 on 2026-01-01 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField(blank=True, null=True)),
                ('category', models.CharField(choices=[('ACADEMIC', 'Academic'), ('SPORTS', 'Sports'), ('CULTURAL', 'Cultural'), ('EXAM', 'Examination'), ('HOLIDAY', 'Holiday'), ('OTHER', 'Other')], max_length=20)),
                ('visibility', models.CharField(choices=[('ALL', 'All Users'), ('TEACHERS_ONLY', 'Teachers Only'), ('STUDENTS_ONLY', 'Students Only')], default='ALL', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to='authentication.adminuser')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'db_table': 'events',
                'ordering': ['event_date', 'event_time'],
                'indexes': [models.Index(fields=['event_date'], name='events_event_d_ec8074_idx'), models.Index(fields=['category'], name='events_categor_a7129c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('announcement_type', models.CharField(choices=[('NOTICE', 'Notice'), ('EXAM_ALERT', 'Exam Alert'), ('HOLIDAY', 'Holiday'), ('URGENT', 'Urgent'), ('GENERAL', 'General')], max_length=20)),
                ('visibility', models.CharField(choices=[('ALL', 'All Users'), ('TEACHERS_ONLY', 'Teachers Only'), ('STUDENTS_ONLY', 'Students Only')], default='ALL', max_length=20)),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_announcements', to='authentication.adminuser')),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'db_table': 'announcements',
                'ordering': ['-is_pinned', '-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='announcemen_created_f85040_idx'), models.Index(fields=['is_pinned'], name='announcemen_is_pinn_52ad7c_idx')],
            },
        ),
    ]
