# Generated by Django 4.2.7 on 2026-01-01 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('academic', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('lecture_time', models.TimeField()),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent')], max_length=10)),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('is_editable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='authentication.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='academic.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='authentication.teacher')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendance Records',
                'db_table': 'attendance',
                'indexes': [models.Index(fields=['date'], name='attendance_date_d460ba_idx'), models.Index(fields=['student', 'date'], name='attendance_student_0943ef_idx'), models.Index(fields=['subject', 'date'], name='attendance_subject_036a70_idx')],
                'unique_together': {('student', 'subject', 'date', 'lecture_time')},
            },
        ),
    ]
